### ISSUE TITLE
request

### ISSUE THREAD

**Issue by FritsOV** [johnaherninfotrack/homeassistant_custom_siemensozw672#3]
I have two questions:

1. could you give some lovelace examples with thermostat and/or other possibility's?
2. in my case i have only one group in my OZW/RVS,  there is an option to use a second group (eg. DP 8771, 8773, 8774)
    i have only one Siemens thermostat (its a bit more it can configure the whole device). Would it be possible to use the second group in a virual way?

**Comment by litinoveweedle** [comment]
HI I use this HACS repo custom integration to simulate/integrate my boiler into climate/thermostat cards:

https://github.com/litinoveweedle/hass-template-climate

In my case configuration.yaml looks like this (you will need to change config to match your OZW entities):
```

climate:
  - platform: climate_template
    name: "Heating HC1"
    modes:
      - "heat"
    preset_modes:
      - "automatic"
      - "comfort"
      - "reduced"
      - "protection"
    min_temp: 10
    max_temp: 30
    temp_step: 0.5
    current_temperature_template: "{{ states('sensor.thrs19_room_temperature_actual_value_hc1') }}"
    preset_mode_template: "{{ states('select.thrs19_operating_mode_hc1') | lower }}"
    set_temperature:
      - service: number.set_value
        target:
          entity_id: "number.thrs19_room_temperature_{% if state_attr('climate.heating_hc1', 'preset_mode') == 'automatic' %}comfort{% else %}{{ state_attr('climate.heating_hc1', 'preset_mode') }}{% endif %}_setpoint_hc1"
        data:  
          value: "{{ temperature }}"
    set_preset_mode:
      - service: select.select_option
        target:
          entity_id: select.thrs19_operating_mode_hc1
        data:
          option: "{{ preset_mode | title }}"

  - platform: climate_template
    name: "Heating HC2"
    modes:
      - "heat"
    preset_modes:
      - "automatic"
      - "comfort"
      - "reduced"
      - "protection"
    min_temp: 10
    max_temp: 30
    temp_step: 0.5
    current_temperature_template: "{{ states('sensor.thrs19_room_temperature_actual_value_hc2') }}"
    preset_mode_template: "{{ states('select.thrs19_operating_mode_hc2') | lower }}"
    set_temperature:
      - service: number.set_value
        target:
          entity_id: "number.thrs19_room_temperature_{% if state_attr('climate.heating_hc2', 'preset_mode') == 'automatic' %}comfort{% else %}{{ state_attr('climate.heating_hc2', 'preset_mode') }}{% endif %}_setpoint_hc2"
        data:  
          value: "{{ temperature }}"
    set_preset_mode:
      - service: select.select_option
        target:
          entity_id: select.thrs19_operating_mode_hc2
        data:
          option: "{{ preset_mode | title }}"

  - platform: climate_template
    name: "Heating DHW"
    modes:
      - "heat"
      - "off"
    min_temp: 10
    max_temp: 60
    temp_step: 1
    current_temperature_template: "{{ states('sensor.thrs19_dhw_temperature_actual_value_top_b3') }}"
    hvac_mode_template: "{% if states('switch.thrs19_dhw_operating_mode') == 'on' %}heat{% else %}off{% endif %}"
    set_temperature:
      - service: number.set_value
        target:
          entity_id: number.thrs19_dhw_temperature_nominal_setpoint
        data:  
          value: "{{ temperature }}"
    set_hvac_mode:
      - condition: template
        value_template: "{{ ( hvac_mode == 'heat' and states('switch.thrs19_dhw_operating_mode') != 'on' ) or ( hvac_mode == 'off' and states('switch.thrs19_dhw_operating_mode') != 'off' ) }}"
      - service: switch.toggle
        target:
          entity_id: switch.thrs19_dhw_operating_mode
```
